export default {
  'base-query': 'baseQuery',
  'canvas': 'canvas',
  'check-token-is-valid': 'checkTokenIsValid',
  'date-utils': 'dateUtils',
  'dirty-data': 'dirtyData',
  'fields-from-error': 'fieldsFromError',
  'filters': 'filters',
  'format-phone-number': 'formatPhoneNumber',
  'get-namespaces': 'getNamespaces',
  'get-persist-data': 'getPersistData',
  'persist-purge-check': 'persistPurgeCheck',
  'phrase': 'phrase',
  'rbac': 'rbac',
  'snack-bar-utils': 'snackBarUtils',
  'styled-props': 'styledProps',
  'utils': 'utils',
  'void-from-promise': 'voidFromPromise',
};
